environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

build: off
install:
  - "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /x64 /release"
  - set PATH=c:\\msys64\\usr\\bin;%PATH%
  - set PATH=c:\\msys64\\mingw64\\bin;%PATH%
  - git submodule update --init --recursive

test_script:
  - make test-all
