environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - git submodule update --init --recursive

build_script:
  - build\appveyor.cmd

test_script:
  - build\appveyortest.cmd

artifacts:
  - path: dist\*
