environment:

  matrix:

    - PYTHONVER: "C:\\Python27"
    - PYTHONVER: "C:\\Python35"
    - PYTHONVER: "C:\\Python27-x64"
    - PYTHONVER: "C:\\Python35-x64"

install:
  - "%PYTHONVER%\\python.exe -m pip install wheel"
  - git submodule update --init --recursive

build_script:
  - build\appveyor.cmd
  - build\appveyortest.cmd

artifacts:
  - path: dist\*
