sudo: required

language: generic

env:
  matrix:
    - BUILDTYPE=3.5.2
    - BUILDTYPE=2.7.12
    - BUILDTYPE=3.4.5
    - BUILDTYPE=pypy-5.3.1
    - BUILDTYPE=lib
    - BUILDTYPE=doc

services:
  - docker

before_install:
  - docker pull adfinissygroup/chirp-jessie

script:
  - ./.scripts/travis_run.sh 
