sudo: required

language: generic

matrix:
  include:
    - os: linux
      env: BUILDTYPE=3.5.2
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: linux
      env: BUILDTYPE=2.7.12
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: linux
      env: BUILDTYPE=3.4.5
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: linux
      env: BUILDTYPE=pypy-5.3.1
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: linux
      env: BUILDTYPE=lib
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: linux
      env: BUILDTYPE=doc
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: linux
      env: BUILDTYPE=bdist
      services: docker
      before_install: docker pull adfinissygroup/chirp-jessie
    - os: osx
      env: BUILDTYPE=osx-test
    - os: osx
      env: BUILDTYPE=osx-bdist
    - os: osx
      env: BUILDTYPE=osx-lib
  allow_failures:
    - os: osx
      env: BUILDTYPE=osx-lib
    - os: osx
      env: BUILDTYPE=osx-bdist

script:
  - ./build/travis_run.sh
