sudo: required

language: generic

env:
  matrix:
    - PYTHON_ENV_VER=3.5.2
    - PYTHON_ENV_VER=2.7.12
    - PYTHON_ENV_VER=3.4.5
    - PYTHON_ENV_VER=pypy-5.3.1

services:
  - docker

before_install:
  - docker pull adfinissygroup/chirp-jessie

script:
  - ./.scripts/travis_run.sh 
