language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install: "pip install -r .requirements.txt"
# command to run tests
script: make test-all
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
